import { FAQType } from "../types";

export const FAQS_DATA: FAQType[] = [
  {
    question: "What is Vulnwatch, how does it work?",
    answer:
      "VulnWatch continuously monitors your domain infrastructure, DNS records, " +
      "SSL certificates, subdomains, and email security, and uses AI to detect " +
      "misconfigurations, exposure risks, and active threats.",
  },
  {
    question: "Do I need technical expertise to use Vulnwatch?",
    answer:
      "Not at all. VulnWatch is built for teams of all technical levels. Every alert comes with plain-English explanations and step-by-step remediation instructions generated by AI.",
  },
  {
    question: "What kind of risk does Vulnwatch detect?",
    answer:
      "VulnWatch monitors for SSL/TLS certificate issues, DNS misconfigurations, " +
      "exposed subdomains, email authentication gaps (SPF, DKIM, and DMARC), " +
      "open ports, and web application vulnerabilities.",
  },
  {
    question: "Is Vulnwatch suitable for small business?",
    answer:
      "Absolutely. VulnWatch was designed with small and growing teams in mind. " +
      "Flexible pricing means you only pay for what you need, and automated " +
      "continuous monitoring gives you enterprise-grade security.",
  },
];

export type FaqCategoryId =
  | "getting-started"
  | "domain-verification"
  | "vulnerability-scanning"
  | "monitoring-alert"
  | "security-privacy"
  | "billing-plans"
  | "others";

export type FaqCategory = {
  id: FaqCategoryId;
  label: string;
};

export type FaqGroup = {
  id: FaqCategoryId;
  title: string;
  questions: FAQType[];
};

export const FAQ_PAGE_CATEGORIES: FaqCategory[] = [
  { id: "getting-started", label: "Getting Started" },
  { id: "domain-verification", label: "Domain Verification" },
  { id: "vulnerability-scanning", label: "Vulnerability Scanning" },
  { id: "monitoring-alert", label: "Monitoring & Alert" },
  { id: "security-privacy", label: "Security & Privacy" },
  { id: "billing-plans", label: "Billing & Plans" },
  { id: "others", label: "Others" },
];

export const FAQ_PAGE_GROUPS: FaqGroup[] = [
  {
    id: "getting-started",
    title: "Getting Started",
    questions: [
      {
        question: "What is VulnWatch",
        answer:
          "VulnWatch is a cybersecurity platform that helps users detect, monitor, and manage vulnerabilities across their domains and systems.",
      },
      {
        question: "How does VulnWatch work?",
        answer:
          "Add your domain, verify ownership, and VulnWatch runs safe public-data checks to find exposed services, weak configuration, and changes that need attention.",
      },
      {
        question: "Who can use VulnWatch?",
        answer:
          "Business owners, product teams, developers, agencies, and security teams can use VulnWatch to understand website risks without heavy tooling.",
      },
    ],
  },
  {
    id: "domain-verification",
    title: "Domain Verification",
    questions: [
      {
        question: "Why do I need to verify my domain?",
        answer:
          "Verification confirms that you own or manage the domain before VulnWatch starts tracking its security posture.",
      },
      {
        question: "How do I verify my domain?",
        answer:
          "You can verify your domain by adding the provided DNS record or uploading the verification file shown in your dashboard.",
      },
      {
        question: "How long does verification take?",
        answer:
          "Most domains verify within a few minutes, though DNS changes can sometimes take longer depending on your provider.",
      },
      {
        question: "What happens if verification fails?",
        answer:
          "VulnWatch will show what could not be confirmed so you can update the DNS record, retry, or contact support.",
      },
    ],
  },
  {
    id: "vulnerability-scanning",
    title: "Vulnerability Scanning",
    questions: [
      {
        question: "What does the scan check for?",
        answer:
          "Scans check public security signals such as SSL status, DNS configuration, exposed services, subdomains, and common website risks.",
      },
      {
        question: "Do I need verification before scanning",
        answer:
          "Yes. Verification is required so scans are only run for domains you own or are authorized to manage.",
      },
      {
        question: "How long does a scan take?",
        answer:
          "A standard scan usually completes in a few minutes, depending on the size of the domain and its public footprint.",
      },
      {
        question: "Can VulnWatch scan subdomains?",
        answer:
          "Yes. VulnWatch can discover and monitor subdomains that are visible from public records and safe checks.",
      },
    ],
  },
  {
    id: "monitoring-alert",
    title: "Monitoring & Alert",
    questions: [
      {
        question: "How does monitoring work?",
        answer:
          "VulnWatch continuously monitors your domain for changes in security posture, including SSL certificate expiration, DNS changes, and newly discovered vulnerabilities.",
      },
      {
        question: "What types of alerts will I receive?",
        answer:
          "You'll receive alerts for critical security issues, certificate expiration warnings, newly discovered vulnerabilities, and configuration changes that may impact security.",
      },
      {
        question: "Can I customize alert settings?",
        answer:
          "Yes. You can configure which alerts you want to receive and set your preferred notification methods through your account settings.",
      },
    ],
  },
  {
    id: "security-privacy",
    title: "Security & Privacy",
    questions: [
      {
        question: "Is my data secure with VulnWatch?",
        answer:
          "Yes. VulnWatch uses industry-standard encryption and security practices to protect your data. We only perform safe, non-intrusive public scans and never store sensitive credentials.",
      },
      {
        question: "What data does VulnWatch collect?",
        answer:
          "VulnWatch only collects publicly available security information about your domains. We do not access internal systems or collect personal data from your websites.",
      },
      {
        question: "Do you share my data with third parties?",
        answer:
          "No. Your security data and scan results are kept confidential and are never shared with third parties without your explicit consent.",
      },
    ],
  },
  {
    id: "billing-plans",
    title: "Billing & Plans",
    questions: [
      {
        question: "What plans are available?",
        answer:
          "VulnWatch offers flexible plans to suit different business needs, from free trials to enterprise solutions. Visit our pricing page for detailed information.",
      },
      {
        question: "Can I upgrade or downgrade my plan?",
        answer:
          "Yes. You can change your plan at any time from your account settings. Changes take effect immediately, and billing is prorated.",
      },
      {
        question: "What payment methods do you accept?",
        answer:
          "We accept major credit cards, debit cards, and support enterprise invoicing for annual plans.",
      },
    ],
  },
  {
    id: "others",
    title: "Others",
    questions: [
      {
        question: "How do I get support?",
        answer:
          "You can reach our support team through the contact form, email, or live chat. We typically respond within 24 hours for standard inquiries.",
      },
      {
        question: "Can I use VulnWatch for multiple domains?",
        answer:
          "Yes. All plans support multiple domain monitoring. The number of domains depends on your chosen plan.",
      },
      {
        question: "Is there a mobile app?",
        answer:
          "Currently, VulnWatch is accessible through a web browser on any device. A dedicated mobile app is planned for future release.",
      },
    ],
  },
];
